### PR TITLE
Toggle player with spacebar

### PR DESCRIPTION
**Pull request by franciscoverpo**

### CODE REVIEW

**Comment by raphamorim** [comment]
Hi @franciscoverpo thanks for the help!
I start review it, but make sense doesn't only pause video using spacebar?

This command is useful, but I think it's not very intuitive.
What do you think of a key with spacebar? Like `command+spacebar`?

**Comment by franciscoverpo** [comment]
VLC does it.
Youtube does it.
Quicktime does it.
I just thing that we could follow the lid.

**Comment by franciscoverpo** [comment]
I change the command
```javascript
key('ctrl+space', togglePlayer)
```

**Comment by raphamorim** [comment]
Merged @franciscoverpo, thanks

**Pull request merged**
